spring.application.name=demo
spring.datasource.url=jdbc:postgresql://lab12-postgres:5432/labdb
spring.datasource.username=postgres
spring.datasource.password=changeme
spring.jpa.hibernate.ddl-auto=update
